# Generated by Django 4.0 on 2022-01-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlblogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelslist',
            name='author',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
    ]
