# Generated by Django 4.0 on 2022-01-09 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlblogs', '0002_alter_users_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('filename', models.TextField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='mlblogs.users')),
            ],
        ),
    ]
